sudo: false
language: php
dist: trusty
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  include:
    - php: "5.3"
      dist: precise
  fast_finish: true
  allow_failures:
    - php: nightly

script:
  - php -dshort_open_tag=Off -dmagic_quotes_gpc=Off tests/index.php
